### ISSUE TITLE
Does this replace the zabbix agent running on the host?

### ISSUE THREAD

**Issue by chihoko** [monitoringartist/zabbix-agent-xxl#10]
Hi,

Great project, thanks for the effort. I assume the Zabbix agent running in the container cannot report metrics about the host system and therefor we need to keep the agent on the host system as well as the agent in the zabbix-agent-xxl container. If so how does Zabbix server deal with two agents from the same host? and is the containerized agent compatible with the new Zabbix agent/server encryption?

**Comment by jangaraj** [comment]
Answers are already in README. Public Docker image `monitoringartist/zabbix-agent-xxl-limited` is limited = only Docker metrics can be monitored + it doesn't support Zabbix 3 agent/server encryption. There is plan to release private paid Docker image `monitoringartist/zabbix-agent-xxl`, which will support host metrics + encryption. There is a link to subscribe for updates about paid version in the README.
