### ISSUE TITLE
letsencrypt ca missing in docker container

### ISSUE THREAD

**Issue by czarly** [monitoringartist/zabbix-agent-xxl#13]
i had the following error when trying to import a configuration template:

docker run --rm \

>   -e XXL_apiurl=https://zabbix.lynx.website \
>   -e XXL_apiuser=xxxxx \
>   -e XXL_apipass=xxxxxx \
>   monitoringartist/zabbix-templates

Post https://zabbix.lynx.website/api_jsonrpc.php: x509: failed to load system roots and no roots provided

according to the following blogpost its probably due to ssl certificate issues.

http://blog.cloud66.com/x509-error-when-using-https-inside-a-docker-container/

i want to add that we use lets encrypt certificates on the server. maybe thats a special root certificate?

cheers!

**Comment by jangaraj** [comment]
Unfortunately Docker image `monitoringartist/zabbix-templates` doesn't support https at the moment.
