### ISSUE TITLE
how to use key docker.xnet?

### ISSUE THREAD

**Issue by JerryDog** [monitoringartist/zabbix-agent-xxl#18]
I deployed zabbix-agent-xxl container on CentOS7.1.
And I set item like this:
    docker.xnet[/{#HCONTAINERID},all,TX-OK]

$docker logs zabbix-agent-xxl
got this error message: "Cannot create /var/run/netns".

**Comment by jangaraj** [comment]
It's in README:

> all docker module container metrics are available except docker.xnet

`docker.xnet` is still experimental key. Use standard zabbix agent and load https://github.com/monitoringartist/zabbix-docker-monitoring.
