### ISSUE TITLE
increase startpoller

### ISSUE THREAD

**Issue by sardigital** [monitoringartist/zabbix-agent-xxl#20]
after edit /usr/local/etc/zabbix_server.conf all returned.

**Comment by jangaraj** [comment]
What a how do you want to achieve?

**Comment by sardigital** [comment]
add Startpooler=50 in zabbix_server.conf

**Comment by jangaraj** [comment]
Sorry you are mixing project. This is zabbix-agent, not server project.

https://github.com/monitoringartist/zabbix-xxl/tree/master/Dockerfile/zabbix-xxl#zabbix-database-as-docker-container -> you need env variable `ZS_Startpooler=50`

**Comment by sardigital** [comment]
oh, thx
