### ISSUE TITLE
add custom low level discovery rule in python

### ISSUE THREAD

**Issue by zbence** [monitoringartist/zabbix-agent-xxl#21]
Hi I want to thank you for handling this awesome project.

I want to ask a little detail about how should I do that. Where place my .py file and which enviroment variable need to set to use as a discovery key in zabbix server?

**Comment by jangaraj** [comment]
How can you add your custom low level discovery rule in python to non-dockerized Zabbix?

**Comment by zbence** [comment]
I saw this post: https://garrigue.re/java-properties-into-json-via-python/
and I want something like this but inside the container but there isn't zabbix_agentd.d directory.
I'm new to zabbix so I just need a comfirm this tutorial can work with this container?

**Comment by jangaraj** [comment]
No, docker image `monitoringartist/zabbix-agent-xxl-limited:latest` is designed only for collecting of Docker metrics. In the theory commercial docker image https://github.com/monitoringartist/zabbix-agent-xxl#paid-zabbix-agent-xxl-docker-image will allow you to add your customizations.

**Comment by zbence** [comment]
Okay thank you for the answer. I decided to use zabbix sender feature for this purpose then.
