### ISSUE TITLE
Agent not running after host restart

### ISSUE THREAD

**Issue by sergsadovyi** [monitoringartist/zabbix-agent-xxl#26]
After Docker host restart all containers return to running state. But dockbix-agent-xxl is in restarting state.
Error log:
`Dockbix Agent XXL v0.0.1b limited version`
`Copyright (C) 2014-2017 Jan Garaj - www.monitoringartist.com`
`Freeware licence - Usage of this binary is restricted to official monitoringartist Docker images only.`
`Error #12 - problem during agent execution`

**Comment by jangaraj** [comment]
It's not a bug. Limited version doesn't support container restart - https://github.com/monitoringartist/dockbix-agent-xxl/issues/7. You need to remove & start container.
