### ISSUE TITLE
Zabbix-agent-xxl error #10

### ISSUE THREAD

**Issue by Abdulkhan2** [monitoringartist/zabbix-agent-xxl#27]
@jangaraj 
I am trying to setup zabbix for our docker containers.
I have setup Zabbix server and DB by following - https://www.zabbix.org/wiki/Dockerized_Zabbix
Zabbix server is up and running fine.

I am having trouble in setting up zabbix xxl agent.
followed this [link](https://github.com/monitoringartist/dockbix-agent-xxl/issues/7) but no luck

Docker command to create agent container 
 **tried both dockbix agent and zabbix agent xxl**
	dzdo docker run \
 --name=dockbix-agent-xxl \
 --net=host \
 --privileged \
 -v /:/rootfs \
 -v /var/run:/var/run \
 -e "ZA_Server=*****" \
 -d monitoringartist/dockbix-agent-xxl-limited:latestst

**For Dockbix i get - Error #12 - Problem during agent execuion**

**zabbix agent -**
 dzdo docker run -i \
 --name=zabbix-agent-xxl \
 -h $(hostname) \
 -p 10050:10050 \
 -v /:/rootfs \
 -e "ZA_Server=<<server hostname>>" \
 -d monitoringartist/zabbix-agent-xxl-limited:latest

**Error log**

Zocker XXL v0.9.4b public limited version
Copyright (C) 2014-2016 Jan Garaj - www.monitoringartist.com 
Freeware licence - Usage of this binary is restricted to official monitoringartist Docker images only.
Starting Zabbix Agent [dcndkr10u]. Zabbix 3.0.4 XXL (2016-08-21) (revision 61185).
Press Ctrl+C to exit.

     9:20170427:181424.744 Starting Zabbix Agent [dcndkr10u]. Zabbix 3.0.4 XXL (2016-08-21) (revision 61185).
     9:20170427:181424.744 **** Enabled features ****
     9:20170427:181424.744 IPv6 support:          YES
     9:20170427:181424.744 TLS support:           YES
     9:20170427:181424.744 **************************
     9:20170427:181424.744 using configuration file: /etc/zabbix/zabbix_agentd.conf
     9:20170427:181424.745 loaded modules: zabbix_module_docker.so, zabbix_module_stress.so
     9:20170427:181424.747 agent #0 started [main process]
    10:20170427:181424.747 agent #1 started [collector]
    11:20170427:181424.748 agent #2 started [listener #1]
    12:20170427:181424.750 agent #3 started [listener #2]
    13:20170427:181424.750 agent #4 started [listener #3]
remove /lib/x86_64-linux-gnu//security: directory not empty
Zocker XXL v0.9.4b public limited version
Copyright (C) 2014-2016 Jan Garaj - www.monitoringartist.com 
Freeware licence - Usage of this binary is restricted to official monitoringartist Docker images only.
Error #10

Docker info

Containers: 35
 Running: 34
 Paused: 0
 Stopped: 1
Images: 27
Server Version: 1.13.1
Storage Driver: overlay
 Backing Filesystem: xfs
 Supports d_type: false
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: active
 NodeID: *********
 Is Manager: true
 ClusterID: *********
 Managers: 1
 Nodes: 1
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
  External CAs:
    cfssl: https://*********1/api/v1/cfssl/sign
 Node Address:********
 Manager Addresses:
  ************
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: aa8187dbd3b7ad67d8e5e3a15115d3eef43a7ed1
runc version: 9df8b306d01f59d3a8029be411de015b7304dd8f
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 3.10.0-514.10.2.el7.x86_64
Operating System: Red Hat Enterprise Linux Server 7.3 (Maipo)
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 15.51 GiB
Name: **********
ID: YD3E:UU4G:6HJ6:NXC7:CN3S:QNSE:F46P:AONP:ZP46:FVX4:VBDF:6XNF
Docker Root Dir: /"***************
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
***************
Live Restore Enabled: false

**Comment by jangaraj** [comment]
It's not a Docker image problem. It's a problem of used docker storage driver (overlay in your case) or xfs.
Please read https://github.com/monitoringartist/dockbix-agent-xxl/issues/16
