### ISSUE TITLE
Cannot open Docker container metric file: '/rootfs/sys/fs/cgroup/memory/docker/.../memory.stat'

### ISSUE THREAD

**Issue by elderone** [monitoringartist/zabbix-agent-xxl#3]
# docker info

Containers: 7
 Running: 4
 Paused: 0
 Stopped: 3
Images: 10
Server Version: 1.10.3
Storage Driver: aufs
 Root Dir: /data/docker/aufs
 Backing Filesystem: extfs
 Dirs: 129
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Plugins:
 Volume: local
 Network: bridge null host
Kernel Version: 3.16.0-4-amd64
Operating System: Debian GNU/Linux 8 (jessie)
OSType: linux
Architecture: x86_64
CPUs: 12
Total Memory: 23.6 GiB
Name: bla-bla
ID: DWGA:Q5HB:VP4Q:HHFD:BPL6:VBR4:LE2Y:KSEE:J3NZ:JDYK:LGIL:VPGF
WARNING: No memory limit support
WARNING: No swap limit support
WARNING: No oom kill disable support
WARNING: No cpu cfs quota support
WARNING: No cpu cfs period support
# ls -1 /sys/fs/cgroup/

blkio
cpu
cpuacct
cpu,cpuacct
cpuset
devices
freezer
net_cls
net_cls,net_prio
net_prio
perf_event
systemd
# cat docker-compose.yml

zabbix-agent-xxl:
  image: monitoringartist/zabbix-agent-xxl-limited:latest
  hostname: bla-bla
  ports:
    - "10050:10050"
  volumes:
    - /:/rootfs
    - /var/run:/var/run
  environment:
    - ZA_Server=bla-bla
    - ZA_ServerActive=bla-bla
    - ZA_Timeout=30

cpu and status get correctly

**Comment by jangaraj** [comment]
Is your _memory_ cgroup subsystem disabled or not enabled?
https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux/6/html/Resource_Management_Guide/sec-memory.html

**Comment by elderone** [comment]
https://lists.debian.org/debian-kernel/2012/01/msg00804.html
please add it to readme
thank you

**Comment by jangaraj** [comment]
Thx, I'll do.
