### ISSUE TITLE
Cannot open metric file: '/sys/fs/cgroup/memory/docker//4cef1a63087d/memory.stat

### ISSUE THREAD

**Issue by yanghuan2016** [monitoringartist/zabbix-agent-xxl#32]
![image](https://user-images.githubusercontent.com/17973776/29015593-29ed2916-7b81-11e7-9748-2ecaa0687e98.png)

The stat file path is full container id, like this
![image](https://user-images.githubusercontent.com/17973776/29015628-60328c96-7b81-11e7-9ac0-f8fffbd37811.png)

**Comment by jangaraj** [comment]
Please follow instruction about debuglevel in the README https://github.com/monitoringartist/dockbix-agent-xxl#support

**Comment by jangaraj** [comment]
Closing. No requested details provided.

**Comment by eternam2** [comment]
me to plz all open agent
