### ISSUE TITLE
Cannot find the [Id] item in the received JSON object

### ISSUE THREAD

**Issue by eskogh** [monitoringartist/zabbix-agent-xxl#33]
Hi,

My logs for dockbix-agent-xxl (not limited) container flooding me with following content:

    16:20170814:110500.780 Cannot find the [Id] item in the received JSON object
    16:20170814:110501.854 Cannot find the [Id] item in the received JSON object
    14:20170814:110501.877 Cannot find the [Id] item in the received JSON object
    16:20170814:110502.920 Cannot find the [Id] item in the received JSON object
    15:20170814:110502.980 Cannot find the [Id] item in the received JSON object
    15:20170814:110503.581 Cannot find the [Id] item in the received JSON object
    14:20170814:110503.638 Cannot find the [Id] item in the received JSON object
    15:20170814:110505.030 Cannot find the [Id] item in the received JSON object
    14:20170814:110505.038 Cannot find the [Id] item in the received JSON object
    16:20170814:110505.051 Cannot find the [Id] item in the received JSON object
    14:20170814:110505.091 Cannot find the [Id] item in the received JSON object
    16:20170814:110505.130 Cannot find the [Id] item in the received JSON object
    14:20170814:110506.135 Cannot find the [Id] item in the received JSON object
    16:20170814:110506.149 Cannot find the [Id] item in the received JSON object
    15:20170814:110506.181 Cannot find the [Id] item in the received JSON object
    16:20170814:110507.206 Cannot find the [Id] item in the received JSON object
    16:20170814:110507.285 Cannot find the [Id] item in the received JSON object
    14:20170814:110509.510 Cannot find the [Id] item in the received JSON object
    16:20170814:110509.510 Cannot find the [Id] item in the received JSON object
    14:20170814:110510.569 Cannot find the [Id] item in the received JSON object
    14:20170814:110511.653 Cannot find the [Id] item in the received JSON object
    15:20170814:110511.674 Cannot find the [Id] item in the received JSON object
    14:20170814:110512.715 Cannot find the [Id] item in the received JSON object
    16:20170814:110512.772 Cannot find the [Id] item in the received JSON object
    16:20170814:110513.831 Cannot find the [Id] item in the received JSON object
    14:20170814:110513.839 Cannot find the [Id] item in the received JSON object
    16:20170814:110514.877 Cannot find the [Id] item in the received JSON object
    14:20170814:110514.882 Cannot find the [Id] item in the received JSON object
    14:20170814:110514.889 Cannot find the [Id] item in the received JSON object
    15:20170814:110515.926 Cannot find the [Id] item in the received JSON object
    16:20170814:110515.968 Cannot find the [Id] item in the received JSON object
    15:20170814:110516.976 Cannot find the [Id] item in the received JSON object
    14:20170814:110516.981 Cannot find the [Id] item in the received JSON object
    16:20170814:110517.014 Cannot find the [Id] item in the received JSON object
    16:20170814:110517.038 Cannot find the [Id] item in the received JSON object
    16:20170814:110517.086 Cannot find the [Id] item in the received JSON object
    15:20170814:110519.220 Cannot find the [Id] item in the received JSON object
    16:20170814:110519.221 Cannot find the [Id] item in the received JSON object
    14:20170814:110520.249 Cannot find the [Id] item in the received JSON object

Got like hundreds of this every minute and the memory of the container is peaking.
I've set memory limit of 500Mb for the container but it crash after a while.

Sometimes it give me a message like:
     14:20170814:110813.103 Cannot open metric file: '/sys/fs/cgroup/memory/docker//2b528c5d9b5cdd362a761d2b78e8be50845e6187c417f37ca3e4a44c85e57177/memory.stat'

**Comment by jangaraj** [comment]
https://github.com/monitoringartist/dockbix-agent-xxl#support
