### ISSUE TITLE
How could i monitor container?

### ISSUE THREAD

**Issue by khoi-thinh** [monitoringartist/zabbix-agent-xxl#34]
Hello,
I went through the read.me but to be honest, it was still very difficult to understand.
So basically, at this moment i have some container like this
![default](https://user-images.githubusercontent.com/13984195/30958390-ef1024f4-a477-11e7-8b7e-1b05db2b4648.jpg)

I run the dockbix-agent-xxl container with Zabbix server IP (installed separately in different instance EC2), also i imported the Dockbix Agent XXL templates.

Now how could i add each container as host in Zabbix server console?

**Comment by jangaraj** [comment]
Unfortunately, that's a generic request for a support, not a real issue.
https://github.com/monitoringartist/dockbix-agent-xxl#support

> how could I add each container as host in Zabbix server console?

You need to create your own template for that. Your start point can be https://raw.githubusercontent.com/monitoringartist/zabbix-docker-monitoring/master/template/UNTESTED-Zabbix-Template-App-Docker-as-host(3.x-only).xml
