### ISSUE TITLE
Restart not working

### ISSUE THREAD

**Issue by ThomasVdBerge** [monitoringartist/zabbix-agent-xxl#37]
I have the dockbix-agent-xxl (limited) working on my environments.

When the server (or docker) restarts. the container should also restart automatically.

However, it stays stuck in the following state:

> Restarting (1) 32 seconds ago

Docker logs reveals the following:

`Dockbix Agent XXL v0.0.5b limited version
Docker image: monitoringartist/dockbix-agent-xxl-limited
Copyright (C) 2014-2017 Jan Garaj - www.monitoringartist.com
Freeware licence - Usage of this binary is restricted to official monitoringartist Docker images only.
Error #12 - problem during agent execution`

Any idea what might cause this?

**Comment by jangaraj** [comment]
Unfortunately, container restart is not supported. You need to remove & start the new container. See issue https://github.com/monitoringartist/dockbix-agent-xxl/issues/7
