### ISSUE TITLE
Ghost Container

### ISSUE THREAD

**Issue by luizhpriotto** [monitoringartist/zabbix-agent-xxl#38]
Hello guys!

I use docker stack and my agents xxl are works fine.

My only problem is LLD in zabbix, because some containers that i already removed, still are monitoring by zabbix like a ghost container and sending triggers for me...

Do you know how to adjust this?

thanks so much...

**Comment by jangaraj** [comment]
Stopped/destroyed containers should be disabled during further LLD discovery. So be patient or tune LLD interval.

**Comment by luizhpriotto** [comment]
I did this to resolve.

Template -> Item -> Keep lost resources period  -> 0.
