### ISSUE TITLE
private paid image limitations

### ISSUE THREAD

**Issue by watanabeyk** [monitoringartist/zabbix-agent-xxl#39]
I found three "General limitaions" in README in github. However, in your product page, it's only one "General limitations" about TLS. What does the "General limitations" mean? I wonder which description is for private paid image.

With private paid image, can I use docker stop/start container command or not ?

**Comment by jangaraj** [comment]
General limitations are applicable for both images - public and also for private => private version doesn't support docker stop/start container command.
