### ISSUE TITLE
Cannot open Docker container metric file: '/rootfs/sys/fs/cgroup/memory/docker/.../memory.stat'

### ISSUE THREAD

**Issue by elderone** [monitoringartist/zabbix-agent-xxl#4]
# cat /etc/centos-release

CentOS Linux release 7.2.1511 (Core)
# uname -a

Linux docker 3.10.0-327.4.5.el7.x86_64 #1 SMP Mon Jan 25 22:07:14 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
# docker -v

Docker version 1.10.1, build 9e83765
# docker version

Client:
 Version:      1.10.1
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   9e83765
 Built:        Thu Feb 11 19:18:46 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.10.1
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   9e83765
 Built:        Thu Feb 11 19:18:46 2016
 OS/Arch:      linux/amd64

**Comment by jangaraj** [comment]
How did you start container? Used OS, ....?

**Comment by elderone** [comment]
this directory exist, but it has one subdir - this zabbix-agent container

**Comment by elderone** [comment]
all containers started by docker-compose

**Comment by elderone** [comment]
other containers started by systemd service

# cat nginx.service

[Unit]
Description=nginx container
Requires=docker.service
After=docker.service

[Service]
Restart=on-failure
RestartSec=3
ExecStart=/usr/local/bin/docker-compose -f /data/nginx/docker-compose.yml up
ExecStop=/usr/local/bin/docker-compose -f /data/nginx/docker-compose.yml stop

[Install]
WantedBy=multi-user.target

**Comment by elderone** [comment]
zabbix-agent started by 

# docker-compose up -d

**Comment by jangaraj** [comment]
Is it problem with memory cgroup #3?

**Comment by elderone** [comment]
thats was on debian and now its resolved...

**Comment by elderone** [comment]
# mount | grep memory

cgroup on /sys/fs/cgroup/memory type cgroup (rw,nosuid,nodev,noexec,relatime,memory)

**Comment by elderone** [comment]
centos already have enabled memory cgroup

**Comment by jangaraj** [comment]
Is your monitored container up and running?

**Comment by elderone** [comment]
yes of course

**Comment by elderone** [comment]
# docker ps

CONTAINER ID        IMAGE                                              COMMAND                  CREATED             STATUS              PORTS                                                             NAMES
2a55ce74a3dc        monitoringartist/zabbix-agent-xxl-limited:latest   "/zocker-xxl"            17 hours ago        Up 17 hours         0.0.0.0:10050->10050/tcp                                          zabbixagent_zabbix-agent_1
6123c6781382        postgres:9.4                                       "/docker-entrypoint.s"   27 hours ago        Up 27 hours         5432/tcp                                                          postgres_postgres_1
2912c32848cb        nginx:latest                                       "nginx -g 'daemon off"   12 days ago         Up 12 days          0.0.0.0:80->80/tcp, 0.0.0.0:443->443/tcp                          nginx_nginx_1

**Comment by jangaraj** [comment]
So which container ID is not able to monitor?

**Comment by elderone** [comment]
# ls -l /sys/fs/cgroup/memory/docker/

итого 0
drwxr-xr-x. 2 root root 0 апр 11 19:17 2a55ce74a3dca16bba37edf8867e1451d95930a855566679ccb3641b0d4c2f76
-rw-r--r--. 1 root root 0 апр 11 19:01 cgroup.clone_children
--w--w--w-. 1 root root 0 апр 11 19:01 cgroup.event_control
-rw-r--r--. 1 root root 0 апр 11 19:01 cgroup.procs
-rw-r--r--. 1 root root 0 апр 11 19:01 memory.failcnt
--w-------. 1 root root 0 апр 11 19:01 memory.force_empty
... other files

**Comment by elderone** [comment]
all containers exclude this zabbix-agent-xxl-limited

**Comment by jangaraj** [comment]
Is memory.stat there and has zabbix user permission to read this file?

**Comment by elderone** [comment]
-r--r--r--. 1 root root 0 апр 11 19:01 memory.stat

**Comment by jangaraj** [comment]
Problem:
Cannot open Docker container metric file: '/rootfs/sys/fs/cgroup/memory/docker/**aae2d2c7b5a71052c61b1a4cf23141742b58a3d0e00b341a106cb6b6508b537b**/memory.stat'

Docker ps:
CONTAINER ID IMAGE COMMAND CREATED STATUS PORTS NAMES
**2a55ce74a3dc** monitoringartist/zabbix-agent-xxl-limited:latest "/zocker-xxl" 17 hours ago Up 17 hours 0.0.0.0:10050->10050/tcp zabbixagent_zabbix-agent_1
**6123c6781382** postgres:9.4 "/docker-entrypoint.s" 27 hours ago Up 27 hours 5432/tcp postgres_postgres_1
**2912c32848cb** nginx:latest "nginx -g 'daemon off" 12 days ago Up 12 days 0.0.0.0:80->80/tcp, 0.0.0.0:443->443/tcp nginx_nginx_1

=> No, your container **aae2d2c7b5a71052c...** is not running => not a problem, containers will be rediscovered (it depends on your LLD rule settings).

I'm closing this issue. Please open new issue, if you have still see this issue, but please provide also proper investigation in the first post - this is not a chat.

**Comment by elderone** [comment]
That container started, but not in this listing. This problem for all started containers exclude zabbix-agent

**Comment by elderone** [comment]
Reopen this issue and read carefully please :-)

**Comment by elderone** [comment]
recreate containers with remove olds resolved this issue
