### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by KinseyNg** [monitoringartist/zabbix-agent-xxl#41]
Hello, after I deployed the agent on my host, the following error was shown. 
Would someone tell me how to solve it? Thank you. 
     8:20180924:013104.498 Starting Zabbix Agent [website]. Zabbix 3.0.4 XXL (2016-08-21) (revision 61185).
     8:20180924:013104.499 **** Enabled features ****
     8:20180924:013104.499 IPv6 support:          YES
     8:20180924:013104.499 TLS support:           YES
     8:20180924:013104.499 **************************
     8:20180924:013104.499 using configuration file: /etc/zabbix/zabbix_agentd.conf
     8:20180924:013104.500 Cannot connect to standard docker's socket /var/run/docker.sock
     8:20180924:013104.500 loaded modules: zabbix_module_docker.so, zabbix_module_stress.so
     8:20180924:013104.503 agent #0 started [main process]
    13:20180924:013104.503 agent #4 started [listener #3]
    12:20180924:013104.504 agent #3 started [listener #2]
    11:20180924:013104.504 agent #2 started [listener #1]
    10:20180924:013104.509 agent #1 started [collector]
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x40596a]

goroutine 1 [running]:
panic(0x7eb920, 0xc82000a070)
	/usr/local/go/src/runtime/panic.go:481 +0x3e6
main.main()
	/root/git/zabbix-agent-xxl-source-code-private/zabbix-agent-3.0-limited/zocker-xxl.go:191 +0x496a
Zocker XXL v0.9.4b public limited version
Copyright (C) 2014-2016 Jan Garaj - www.monitoringartist.com 
Freeware licence - Usage of this binary is restricted to official monitoringartist Docker images only.
Error #10

**Comment by jangaraj** [comment]
You are using an obsolete image `monitoringartist/zabbix-agent-xxl-limited`, you newer https://hub.docker.com/r/monitoringartist/dockbix-agent-xxl-limited/
