### ISSUE TITLE
Can't see any data about containers

### ISSUE THREAD

**Issue by pan112358** [monitoringartist/zabbix-agent-xxl#44]
I deployed dockbix-agent-xxl in my K8s node and connect to Zabbix 4.0 server, the containers can be discovered, but no data is updated, even for the container created by docker itself.
![1](https://user-images.githubusercontent.com/35713208/50476140-f26d3880-0a01-11e9-95ed-93264e825cce.PNG)

**Comment by jangaraj** [comment]
I guess you will need to compile/deploy dev branch https://github.com/monitoringartist/zabbix-docker-monitoring/tree/cgroup-parent for your K8s

**Comment by pan112358** [comment]
Thanks for the quick response, I will try
