### ISSUE TITLE
license is not clear if it's allowed to be copied in a form of docker copy

### ISSUE THREAD

**Issue by fumiya-kobayashi** [monitoringartist/zabbix-agent-xxl#49]
License document states that one cannot copy binary files dockbix-agent-xxl and zabbix_agentd included in Docker image monitoringartist/dockbix-agent-xxl-limited.
However, it's not clear if it's allowed to copy the docker image itself.

More clearly, is it allowed to execute following commands to monitoringartist/dockbix-agent-xxl-limited ?

- docker pull
- docker run

I am going to use the docker image in our environment and would like to confirm it does not violate the license.
My apologies for asking trivial questions, but my legal department requested me to make it clear.

Thank you in advance.

Kobayashi

**Comment by jangaraj** [comment]
Yes, you can copy Docker image (technically, `docker pull` creates copy of the image), but you can't copy binaries from `monitoringartist/dockbix-agent-xxl-limited` (image disassembling) to other images/containers.

**Comment by fumiya-kobayashi** [comment]
Thanks for the reply!
I'm forwarding your response to my legal department and things will be resolved.
