### ISSUE TITLE
Can DockBix Agent  work on AWS Fargate

### ISSUE THREAD

**Issue by OrwinLopes** [monitoringartist/zabbix-agent-xxl#50]
With AWS Fargate there is no more concept of docker host... so if we need to monitor the containers ...is it possible to deploy dockbix agent as a task in the application container say for instance a simple Web Application to monitor the container metrics ? nothing much is available on AWS site or zabbix site on this .... need help on this ? or only way is to pump the metrics from aws cloudwatch to zabbix via the  integration available on the zabbix site.

**Comment by jangaraj** [comment]
Sorry, deployment on different platforms (AWS Fargate/ECS/EKS/EC2, Cloud Foundry, Kubernetes, Docker Swarm, ...) is not in the scope of this project. Please read a doc or just try it.
