### ISSUE TITLE
Privileged flag not documented

### ISSUE THREAD

**Issue by christamlyn-bridge** [monitoringartist/zabbix-agent-xxl#53]
In the readme all examples use the 
`--privileged `
flag but its not documented.

Docker Swarm does not support the privileged flag, does this mean we cannot use this image?

https://github.com/moby/moby/issues/24862

**Comment by jangaraj** [comment]
In theory you don't need `--privileged` flag. But you have to configure container permissions/capabilities to read/write to docker socket and OS cgroups.
