### ISSUE TITLE
Require Linux/ARM64 docker image for monitoringartist/dockbix-agent-xxl-limited.

### ISSUE THREAD

**Issue by odidev** [monitoringartist/zabbix-agent-xxl#57]
Hi Team,

I am trying to build monitoringartist/dockbix-agent-xxl-limited docker image on Linux/ARM64. 

Although, I am unable to locate docker file in the repository. I have also explored [docker hub](https://hub.docker.com/r/monitoringartist/dockbix-agent-xxl-limited) repository as well but there is no information about any source repo there too.  

Do you have any plans for releasing arm64 image?

It would be helpful if you can provide the details about Docker file. 

I will do the required changes and raise PR on the same.

**Comment by jangaraj** [comment]
Unfortunately, whole source code is not open sourced - Docker image is only a freeware. Base is https://github.com/monitoringartist/zabbix-docker-monitoring + there is wrapper golang binary, which prepares environment and start zabbix agent, with the best suitable parameters for the containers (e.g. output to stdout/stderr, ....). Unfortunately, I don't have a plan to release it for other architectures.  You may use https://github.com/monitoringartist/zabbix-docker-monitoring in your own Docker image. I would go with Zabbix agent 2 (Golang based), which has also now support for Docker monitoring.  Thanks to Golang you can do a cross architecture compiling to static binary, which is the best option for Docker images.
