### ISSUE TITLE
"-v /var/run:/var/run" required in docker-compose.yml?

### ISSUE THREAD

**Issue by kujiy** [monitoringartist/zabbix-agent-xxl#8]
Hi. Thank you for sharing your great project. I noticed something. Your readme says it needs "-v /var/run:/var/run " but your docker-compose.yml doesn't have it.
Which is correct?

**Comment by kujiy** [comment]
I sent PR about this.

Here are my current environment.

``` sh
$ root@:/zabbix-agent# docker --version
Docker version 1.11.1, build 5604cbe
$ root@cr:/zabbix-agent# docker-compose --version
docker-compose version 1.7.1, build 6c29830
```

**Comment by jangaraj** [comment]
`-v /var/run:/var/run` is required for Ubuntu/Debian. It's in doc for every OS, just to keep doc simple and clear. I'll update docker-compose.yml later.
